aslurm -gpt None -gpus None -mt 12 -cn haicore_1gpu \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/org__15_04_2025__23_15__87LB ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/org__15_04_2025__23_15__87LB/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/org__15_04_2025__23_15__87LB/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/org__15_04_2025__23_15__JKIa ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/org__15_04_2025__23_15__JKIa/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/org__15_04_2025__23_15__JKIa/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/org__15_04_2025__23_15__peH9 ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/org__15_04_2025__23_15__peH9/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/org__15_04_2025__23_15__peH9/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/org__15_04_2025__23_15__W8ql ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/org__15_04_2025__23_15__W8ql/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/org__15_04_2025__23_15__W8ql/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/cf1__15_04_2025__23_11__5VE2 ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf1__15_04_2025__23_11__5VE2/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf1__15_04_2025__23_11__5VE2/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/cf1__15_04_2025__23_11__J2Mf ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf1__15_04_2025__23_11__J2Mf/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf1__15_04_2025__23_11__J2Mf/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/cf1__15_04_2025__23_11__MvrC ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf1__15_04_2025__23_11__MvrC/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf1__15_04_2025__23_11__MvrC/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/cf1__15_04_2025__23_11__pxMi ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf1__15_04_2025__23_11__pxMi/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf1__15_04_2025__23_11__pxMi/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/cf2__15_04_2025__23_13__MObg ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf2__15_04_2025__23_13__MObg/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf2__15_04_2025__23_13__MObg/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/cf2__15_04_2025__23_13__VrVp ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf2__15_04_2025__23_13__VrVp/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf2__15_04_2025__23_13__VrVp/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/cf2__15_04_2025__23_13__WNsz ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf2__15_04_2025__23_13__WNsz/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf2__15_04_2025__23_13__WNsz/trajectory.dcd" \
    cmd "conda activate md_aggregation ; cd /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/simulate_aggregation/cf2__15_04_2025__23_13__XCnm ; python /home/iti/tm4030/Programming/md_aggregation/ClusterAnalysis/runClusterAnalysis.py -hb -r 3 -e 4300 -solv HOH -ex DMS CL NA -top /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf2__15_04_2025__23_13__XCnm/topology.pdb -traj /home/iti/tm4030/Programming/md_aggregation/md_aggregation/experiments/results/aggregation_simulation/cf2__15_04_2025__23_13__XCnm/trajectory.dcd" \

