name: md_simulation
channels:
  - conda-forge
dependencies:
  - python=3.11.8
  - pip=24.0
  - openmm=8.0.0
  - openmmtools=0.23.1
  - cudatoolkit=11.4.3
  - mdtraj=1.9.9
  - pyemma=2.5.12
  - openff-toolkit
  - pip:
    - rdkit